export const COFFEE_ITEMS = [
  {
    id: 1,
    name: 'Espresso',
    category: 'Coffee',
    price: 'Rp 20.000',
    description: 'Pure, bold, and concentrated',
    longDescription: 'Rich and intense, our espresso is the foundation of all our specialty drinks.',
    image: 'espresso',
  },
  {
    id: 2,
    name: 'Cappuccino',
    category: 'Coffee',
    price: 'Rp 28.000',
    description: 'Equal parts espresso, milk, and foam',
    longDescription: 'Perfectly balanced with a velvety microfoam for the ultimate cappuccino experience.',
    image: 'cappuccino',
  },
  {
    id: 3,
    name: 'Iced Latte',
    category: 'Coffee',
    price: 'Rp 30.000',
    description: 'Cold milk with smooth espresso',
    longDescription: 'Refreshingly cold with our smooth, creamy espresso blend.',
    image: 'iced-latte',
  },
  {
    id: 4,
    name: 'Caramel Latte',
    category: 'Coffee',
    price: 'Rp 32.000',
    description: 'Espresso with caramel sweetness',
    longDescription: 'Indulgent caramel notes complement our signature espresso perfectly.',
    image: 'caramel-latte',
  },
  {
    id: 5,
    name: 'Americano',
    category: 'Coffee',
    price: 'Rp 22.000',
    description: 'Espresso with hot water',
    longDescription: 'Bold yet smooth, a classic choice for espresso lovers.',
    image: 'americano',
  },
  {
    id: 6,
    name: 'Spanish Latte',
    category: 'Coffee',
    price: 'Rp 30.000',
    description: 'Sweetened milk with espresso',
    longDescription: 'A creamy, slightly sweet take on the classic latte.',
    image: 'spanish-latte',
  },
  {
    id: 7,
    name: 'Mocha',
    category: 'Coffee',
    price: 'Rp 32.000',
    description: 'Espresso with chocolate and milk',
    longDescription: 'Rich chocolate meets smooth espresso for a delightful treat.',
    image: 'mocha',
  },
  {
    id: 8,
    name: 'Flat White',
    category: 'Coffee',
    price: 'Rp 30.000',
    description: 'Velvety milk with espresso base',
    longDescription: 'Silky smooth microfoam creates the perfect canvas for espresso.',
    image: 'flat-white',
  },
];
